name: Publish XBPS Repository

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: read

jobs:
  publish:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/void-linux/void-glibc-full:latest

    steps:
      - uses: actions/checkout@v4

      - name: Download artifact
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir artifact

          curl -L \
            -H "Authorization: Bearer $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/8581634335/zip" \
            -o artifact.zip

          unzip artifact.zip -d artifact

      - name: Create repository
        run: |
          mkdir -p repo/x86_64

          find artifact -maxdepth 1 -type f -name "*.xbps" -exec cp {} repo/x86_64/ \;

          xbps-rindex -fa repo/x86_64/*.xbps

      - name: Commit repository
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add repo/x86_64

          git commit -m "Update XBPS repository" || exit 0

          git push