name: Generate signing key

on:
  workflow_dispatch:

jobs:
  genkey:
    runs-on: ubuntu-latest
    steps:
      - name: Generate RSA key
        run: |
          openssl genrsa -out privkey.pem 4096
          cat privkey.pem
